# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\main_page_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.setEnabled(True)
        MainPage.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainPage.sizePolicy().hasHeightForWidth())
        MainPage.setSizePolicy(sizePolicy)
        MainPage.setMinimumSize(QtCore.QSize(1200, 800))
        MainPage.setMaximumSize(QtCore.QSize(1200, 800))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        MainPage.setFont(font)
        MainPage.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainPage)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {background-color: rgb(30, 30, 30);}")
        self.centralwidget.setObjectName("centralwidget")
        self.app_name = QtWidgets.QLabel(self.centralwidget)
        self.app_name.setGeometry(QtCore.QRect(490, 20, 202, 36))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("QLabel#app_name {\n"
"    background-color: transparent;\n"
"    color: rgb(224, 139, 70);\n"
"}")
        self.app_name.setObjectName("app_name")
        self.films_list = QtWidgets.QListWidget(self.centralwidget)
        self.films_list.setGeometry(QtCore.QRect(40, 190, 751, 571))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.films_list.setFont(font)
        self.films_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.films_list.setStyleSheet("QListWidget#films_list {\n"
"    border: 0;\n"
"    background-color: rgb(47, 47, 47);\n"
"    color: rgb(203, 116, 47);\n"
"    border-bottom-right-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    letter-spacing: 0.17px;\n"
"    padding: 10px;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QListWidget#films_list::item {\n"
"    border-radius: 4px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"QListWidget#films_list::item:hover {background-color: rgb(30, 30, 30);}\n"
"QListWidget#films_list::item:selected {color: rgb(224, 139, 70);}\n"
"\n"
"")
        self.films_list.setFrameShape(QtWidgets.QFrame.Box)
        self.films_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.films_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.films_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.films_list.setObjectName("films_list")
        self.search_film = QtWidgets.QLineEdit(self.centralwidget)
        self.search_film.setGeometry(QtCore.QRect(40, 78, 981, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.search_film.setFont(font)
        self.search_film.setStyleSheet("QLineEdit#search_film {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"selection-background-color: rgb(203, 116, 47);\n"
"selection-color: rgb(47, 47, 47);\n"
"border-top-left-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border: 3px solid rgb(203, 116, 47);\n"
"border-right-width: 0;\n"
"}")
        self.search_film.setFrame(True)
        self.search_film.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.search_film.setCursorPosition(0)
        self.search_film.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_film.setObjectName("search_film")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(1020, 78, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.search_button.setFont(font)
        self.search_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_button.setStyleSheet("QPushButton#search_button {\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(203, 116, 47, 255), stop:1 rgba(231, 146, 78, 255));\n"
"color: rgb(0,0,0);\n"
"border: 0;\n"
"border-top-right-radius: 8px;\n"
"border-bottom-right-radius: 8px;}\n"
"\n"
"QPushButton#search_button:pressed {border: 1px solid rgb(47, 47, 47);}")
        self.search_button.setObjectName("search_button")
        self.film_label = QtWidgets.QLabel(self.centralwidget)
        self.film_label.setGeometry(QtCore.QRect(40, 160, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.film_label.setFont(font)
        self.film_label.setStyleSheet("QLabel#film_label {\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(203, 116, 47, 255), stop:1 rgba(231, 146, 78, 255));\n"
"color: rgb(47, 47, 47);\n"
"border: 0;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"letter-spacing: 0.5px;\n"
"}")
        self.film_label.setAlignment(QtCore.Qt.AlignCenter)
        self.film_label.setObjectName("film_label")
        self.filter_label = QtWidgets.QLabel(self.centralwidget)
        self.filter_label.setGeometry(QtCore.QRect(805, 190, 381, 22))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.filter_label.setFont(font)
        self.filter_label.setStyleSheet("QLabel#filter_label {\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(203, 116, 47, 255), stop:1 rgba(231, 146, 78, 255));\n"
"color: rgb(47, 47, 47);\n"
"border: 0;\n"
"border-radius: 3px;\n"
"letter-spacing: 0.5px;\n"
"}")
        self.filter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_label.setObjectName("filter_label")
        self.genre_label = QtWidgets.QLabel(self.centralwidget)
        self.genre_label.setGeometry(QtCore.QRect(810, 250, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.genre_label.setFont(font)
        self.genre_label.setStyleSheet("QLabel#genre_label {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"border: 0;\n"
"border-top-left-radius: 3px;\n"
"border-bottom-left-radius: 3px;\n"
"letter-spacing: 1px;\n"
"padding-left: 0px;\n"
"}")
        self.genre_label.setAlignment(QtCore.Qt.AlignCenter)
        self.genre_label.setObjectName("genre_label")
        self.start_year_label = QtWidgets.QLabel(self.centralwidget)
        self.start_year_label.setGeometry(QtCore.QRect(810, 300, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.start_year_label.setFont(font)
        self.start_year_label.setStyleSheet("QLabel#start_year_label {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"border: 0;\n"
"border-top-left-radius: 3px;\n"
"border-bottom-left-radius: 3px;\n"
"letter-spacing: -0.5px;\n"
"}\n"
"")
        self.start_year_label.setAlignment(QtCore.Qt.AlignCenter)
        self.start_year_label.setObjectName("start_year_label")
        self.genre_box = QtWidgets.QComboBox(self.centralwidget)
        self.genre_box.setGeometry(QtCore.QRect(990, 250, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.genre_box.setFont(font)
        self.genre_box.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.genre_box.setStyleSheet("")
        self.genre_box.setCurrentText("")
        self.genre_box.setObjectName("genre_box")
        self.start_year_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.start_year_spin.setGeometry(QtCore.QRect(990, 300, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.start_year_spin.setFont(font)
        self.start_year_spin.setStyleSheet("QSpinBox#start_year_spin {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"selection-background-color: rgb(203, 116, 47);\n"
"selection-color: rgb(47, 47, 47);\n"
"border: 0;\n"
"border-top-right-radius: 3px;\n"
"border-bottom-right-radius: 3px;\n"
"letter-spacing: 0.2px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"QSpinBox#start_year_spin::down-button {\n"
"    top: 2px;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}\n"
"\n"
"QSpinBox#start_year_spin::up-button {\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}\n"
"")
        self.start_year_spin.setAlignment(QtCore.Qt.AlignCenter)
        self.start_year_spin.setObjectName("start_year_spin")
        self.reset_filter_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_filter_button.setEnabled(False)
        self.reset_filter_button.setGeometry(QtCore.QRect(810, 520, 371, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_filter_button.sizePolicy().hasHeightForWidth())
        self.reset_filter_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.reset_filter_button.setFont(font)
        self.reset_filter_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_filter_button.setStyleSheet("QPushButton#reset_filter_button {\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(203, 116, 47, 255), stop:1 rgba(231, 146, 78, 255));\n"
"color: rgb(0,0,0);\n"
"border: 0;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#reset_filter_button:pressed {border: 1px solid rgb(47, 47, 47);}\n"
"QPushButton#reset_filter_button:disabled {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(203, 116, 47, 190), stop:1 rgba(231, 146, 78, 190));\n"
"    color: rgb(47, 47, 47);\n"
"}")
        self.reset_filter_button.setIconSize(QtCore.QSize(20, 20))
        self.reset_filter_button.setCheckable(False)
        self.reset_filter_button.setChecked(False)
        self.reset_filter_button.setFlat(False)
        self.reset_filter_button.setObjectName("reset_filter_button")
        self.end_year_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.end_year_spin.setGeometry(QtCore.QRect(990, 350, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.end_year_spin.setFont(font)
        self.end_year_spin.setStyleSheet("QSpinBox#end_year_spin {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"selection-background-color: rgb(203, 116, 47);\n"
"selection-color: rgb(47, 47, 47);\n"
"border: 0;\n"
"border-top-right-radius: 3px;\n"
"border-bottom-right-radius: 3px;\n"
"letter-spacing: 0.2px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"QSpinBox#end_year_spin::down-button {\n"
"    top: 2px;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}\n"
"\n"
"QSpinBox#end_year_spin::up-button {\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}")
        self.end_year_spin.setAlignment(QtCore.Qt.AlignCenter)
        self.end_year_spin.setObjectName("end_year_spin")
        self.end_year_label = QtWidgets.QLabel(self.centralwidget)
        self.end_year_label.setGeometry(QtCore.QRect(810, 350, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.end_year_label.setFont(font)
        self.end_year_label.setStyleSheet("QLabel#end_year_label {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"border: 0;\n"
"border-top-left-radius: 3px;\n"
"border-bottom-left-radius: 3px;\n"
"letter-spacing: -0.5px;\n"
"}\n"
"")
        self.end_year_label.setAlignment(QtCore.Qt.AlignCenter)
        self.end_year_label.setObjectName("end_year_label")
        self.min_duration_label = QtWidgets.QLabel(self.centralwidget)
        self.min_duration_label.setGeometry(QtCore.QRect(810, 400, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.min_duration_label.setFont(font)
        self.min_duration_label.setStyleSheet("QLabel#min_duration_label {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"border: 0;\n"
"border-top-left-radius: 3px;\n"
"border-bottom-left-radius: 3px;\n"
"letter-spacing: -0.5px;\n"
"word-spacing: -7px;\n"
"}\n"
"")
        self.min_duration_label.setAlignment(QtCore.Qt.AlignCenter)
        self.min_duration_label.setObjectName("min_duration_label")
        self.min_duration_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.min_duration_spin.setGeometry(QtCore.QRect(990, 400, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.min_duration_spin.setFont(font)
        self.min_duration_spin.setStyleSheet("QSpinBox#min_duration_spin {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"selection-background-color: rgb(203, 116, 47);\n"
"selection-color: rgb(47, 47, 47);\n"
"border: 0;\n"
"border-top-right-radius: 3px;\n"
"border-bottom-right-radius: 3px;\n"
"letter-spacing: 0.2px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"QSpinBox#min_duration_spin::down-button {\n"
"    top: 2px;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}\n"
"\n"
"QSpinBox#min_duration_spin::up-button {\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}")
        self.min_duration_spin.setAlignment(QtCore.Qt.AlignCenter)
        self.min_duration_spin.setObjectName("min_duration_spin")
        self.max_duration_label = QtWidgets.QLabel(self.centralwidget)
        self.max_duration_label.setGeometry(QtCore.QRect(810, 450, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.max_duration_label.setFont(font)
        self.max_duration_label.setStyleSheet("QLabel#max_duration_label {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"border: 0;\n"
"border-top-left-radius: 3px;\n"
"border-bottom-left-radius: 3px;\n"
"letter-spacing: -0.5px;\n"
"word-spacing: -7px;\n"
"}\n"
"")
        self.max_duration_label.setAlignment(QtCore.Qt.AlignCenter)
        self.max_duration_label.setObjectName("max_duration_label")
        self.max_duration_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.max_duration_spin.setGeometry(QtCore.QRect(990, 450, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.max_duration_spin.setFont(font)
        self.max_duration_spin.setStyleSheet("QSpinBox#max_duration_spin {\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(203, 116, 47);\n"
"selection-background-color: rgb(203, 116, 47);\n"
"selection-color: rgb(47, 47, 47);\n"
"border: 0;\n"
"border-top-right-radius: 3px;\n"
"border-bottom-right-radius: 3px;\n"
"letter-spacing: 0.2px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"QSpinBox#max_duration_spin::down-button {\n"
"    top: 2px;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}\n"
"\n"
"QSpinBox#max_duration_spin::up-button {\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}")
        self.max_duration_spin.setAlignment(QtCore.Qt.AlignCenter)
        self.max_duration_spin.setObjectName("max_duration_spin")
        self.add_film_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_film_button.setGeometry(QtCore.QRect(640, 160, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_film_button.sizePolicy().hasHeightForWidth())
        self.add_film_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.add_film_button.setFont(font)
        self.add_film_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_film_button.setStyleSheet("QPushButton#add_film_button {\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(203, 116, 47, 255), stop:1 rgba(231, 146, 78, 255));\n"
"color: rgb(0,0,0);\n"
"border: 0;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#add_film_button:pressed {border: 1px solid rgb(47, 47, 47);}\n"
"")
        self.add_film_button.setIconSize(QtCore.QSize(20, 20))
        self.add_film_button.setCheckable(False)
        self.add_film_button.setChecked(False)
        self.add_film_button.setFlat(False)
        self.add_film_button.setObjectName("add_film_button")
        MainPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainPage)
        self.genre_box.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Films Going"))
        self.app_name.setText(_translate("MainPage", "Films Going"))
        self.search_film.setPlaceholderText(_translate("MainPage", "Найти фильм..."))
        self.search_button.setText(_translate("MainPage", "Поиск"))
        self.film_label.setText(_translate("MainPage", "Все фильмы"))
        self.filter_label.setText(_translate("MainPage", "Фильтры"))
        self.genre_label.setText(_translate("MainPage", "Жанр"))
        self.start_year_label.setText(_translate("MainPage", "С какого года"))
        self.reset_filter_button.setText(_translate("MainPage", "Сбросить"))
        self.end_year_label.setText(_translate("MainPage", "По какой год"))
        self.min_duration_label.setText(_translate("MainPage", "Мин. длительность"))
        self.max_duration_label.setText(_translate("MainPage", "Макс. длительность"))
        self.add_film_button.setText(_translate("MainPage", "Добавить"))
